from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mysql_api import ensure_s01_business_tables, execute, query_one  # noqa: E402
from seed_e03_e04_detail_v0_6 import ensure_columns, seed_rows  # noqa: E402


def main() -> int:
    """
    Restore the stable acceptance baseline after write-through ingestion tests.

    The intelligent-ingestion tests intentionally create real business records
    so that dashboard indicators can prove they are no longer mock-only. Those
    writes are valid during the test, but the shared demo database must be reset
    before the next KPI acceptance run.
    """

    ensure_columns()
    ensure_s01_business_tables()

    # Remove business records generated by ingestion smoke tests. Baseline E03
    # data lives in 710001-710009 and is reseeded below.
    execute("DELETE FROM env_monitoring_record WHERE document_id IS NOT NULL OR id >= 410100")
    execute("DELETE FROM env_issue_record WHERE document_id IS NOT NULL OR id >= 420100")
    execute("DELETE FROM water_protection_issue WHERE id >= 710010")

    # Defensive cleanup for other target tables that may be used by future
    # ingestion tests. Current seeded KPI ranges remain untouched.
    execute("DELETE FROM carbon_emission_activity WHERE id >= 720100")
    execute("DELETE FROM safety_incident_record WHERE document_id IS NOT NULL OR id >= 530100")
    execute("DELETE FROM safety_risk_point WHERE document_id IS NOT NULL OR id >= 730100")
    execute("DELETE FROM labor_dispute_record WHERE document_id IS NOT NULL OR id >= 510100")
    execute("DELETE FROM appeal_record WHERE document_id IS NOT NULL OR id >= 520100")
    execute("DELETE FROM permit_record WHERE id >= 740100")
    execute("DELETE FROM permit_record WHERE document_id IS NOT NULL")
    execute("DELETE FROM compliance_procedure WHERE document_id IS NOT NULL OR id >= 310100")
    execute("DELETE FROM rectification_record WHERE document_id IS NOT NULL OR id >= 760100")
    execute("DELETE FROM salary_payment_record WHERE document_id IS NOT NULL OR id >= 740100")

    execute("UPDATE compliance_material_gap SET status = '待提交', action_text = '上传' WHERE id IN (340001, 340002, 340003)")
    execute("UPDATE compliance_material_gap SET status = '逾期', action_text = '补交' WHERE id = 340004")
    execute("DELETE FROM compliance_material_gap WHERE id >= 340100")

    seed_rows()

    e01_exceed = query_one(
        """
        SELECT COALESCE(SUM(exceed_count), 0) AS c
        FROM env_monitoring_record
        WHERE monitor_date >= '2026-07-01'
          AND monitor_date < '2026-08-01'
          AND exceed_count > 0
        """
    )["c"]
    e02_open = query_one("SELECT COUNT(*) AS c FROM env_issue_record WHERE issue_status <> '已闭环'")["c"]
    e03_open = query_one("SELECT COUNT(*) AS c FROM water_protection_issue WHERE issue_status <> '已闭环'")["c"]
    s02_active = query_one(
        """
        SELECT COUNT(*) AS c
        FROM safety_risk_point
        WHERE risk_level IN ('重大', '较大') AND control_status <> '已销号'
        """
    )["c"]
    s01_interrupt = query_one("SELECT COUNT(*) AS c FROM safety_incident_record WHERE interrupt_counting = 1 AND incident_date <= '2026-07-13'")["c"]
    s03_open = query_one("SELECT COUNT(*) AS c FROM labor_dispute_record WHERE status <> '已办结'")["c"]
    s04_open = query_one("SELECT COUNT(*) AS c FROM appeal_record WHERE status <> '已办结'")["c"]
    g01_open = query_one("SELECT COUNT(*) AS c FROM compliance_procedure WHERE status <> '已完成'")["c"]
    g02_open = query_one("SELECT COUNT(*) AS c FROM permit_record WHERE status IN ('临期', '逾期')")["c"]
    g03_open = query_one("SELECT COUNT(*) AS c FROM rectification_record WHERE status <> '已关闭'")["c"]
    g04_open = query_one("SELECT COUNT(*) AS c FROM compliance_material_gap WHERE status <> '已补齐'")["c"]
    if int(e01_exceed) != 2:
        raise AssertionError(f"E01 baseline restore failed, exceed count={e01_exceed}")
    if int(e02_open) != 5:
        raise AssertionError(f"E02 baseline restore failed, open count={e02_open}")
    if int(e03_open) != 7:
        raise AssertionError(f"E03 baseline restore failed, open count={e03_open}")
    if int(s02_active) != 6:
        raise AssertionError(f"S02 baseline restore failed, active count={s02_active}")
    if int(s01_interrupt) != 0:
        raise AssertionError(f"S01 baseline restore failed, interrupt incident count={s01_interrupt}")
    if int(s03_open) != 4:
        raise AssertionError(f"S03 baseline restore failed, open count={s03_open}")
    if int(s04_open) != 3:
        raise AssertionError(f"S04 baseline restore failed, open count={s04_open}")
    if int(g01_open) != 5:
        raise AssertionError(f"G01 baseline restore failed, open count={g01_open}")
    if int(g02_open) != 5:
        raise AssertionError(f"G02 baseline restore failed, open count={g02_open}")
    if int(g03_open) != 6:
        raise AssertionError(f"G03 baseline restore failed, open count={g03_open}")
    if int(g04_open) != 4:
        raise AssertionError(f"G04 baseline restore failed, open count={g04_open}")

    print("[PASS] acceptance baseline restored: E01=2, E02=5, E03=7, S02=6, S03=4, S04=3, G01=5, G02=5, G03=6, G04=4")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
